
name: 'dbt_project_2'
version: '1.0.0'
config-version: 2

profile: 'northwind'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  northwind:
    datamart:
      +materialized: table
      +schema: datamart
    staging:
      +materialized: table
      +schema: staging